{% set name = "oiffile" %}
{% set version = "2025.5.10" %}
{% set sha256 = "c49a0474cdaa6942be3814c63e00d2510cd2fcc287496f3171ba56cb2d01c9f6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - tifffile

test:
  imports:
    - oiffile
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com/
  summary: Read Olympus image files (OIF and OIB)
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Oiffile is a Python library to read image and metadata from Olympus Image Format files. OIF is the native file format of the Olympus FluoView(tm) software for confocal microscopy.
  dev_url: https://github.com/cgohlke/oiffile/

extra:
  recipe-maintainers:
    - cgohlke
    - goanpeca
    - jaimergp
