{% set name = "oiffile" %}
{% set version = "2022.9.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oiffile-{{ version }}.tar.gz
  sha256: 3288717c83d882ab7d07463252edee764308daf26533ba88fd8883bf20f318e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.15.1
    - python >=3.8
    - tifffile >=2020.6.3

test:
  imports:
    - oiffile
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Olympus(r) image files (OIF and OIB)
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/oiffile/

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
