{% set name = "oiffile" %}
{% set version = "2022.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oiffile-{{ version }}.tar.gz
  sha256: e13a26613b89cb52e0e641d07f5e40394ce7e2aafc922903ae5190e655d5140f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.15.1
    - python >=3.8
    - tifffile >=2020.6.3

test:
  imports:
    - oiffile
  commands:
    - pip list
    - pip check
    - python -c "from oiffile import OifFile"
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read Olympus(r) image files (OIF and OIB)
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/oiffile/

extra:
  recipe-maintainers:
    - conda-forge/napari
